### PR TITLE
__init__.py

### PR DESCRIPTION
**Pull request by Praveensenpai**
added type hint and converted to single line

### CODE REVIEW

**Review by Xyndra — APPROVED** [review]
Seems good, might take a bit until I can upload to _pip_ though

**Comment by Xyndra** [comment]
@Praveensenpai would you be interested in being the maintainer of this project?

**Comment by Praveensenpai** [comment]
> @Praveensenpai would you be interested in being the maintainer of this project?

okay, cool.

**Comment by Xyndra** [comment]
what is your pypi username?

**Comment by Praveensenpai** [comment]
> what is your pypi username?

https://pypi.org/user/praveensenpai/

**Pull request merged**
